import Header from "@/components/Header";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "ShinodaLabs | Resumo",
  description: "Generated by create next app",
};

export default function ResumePage() {
  return (
    <div className="w-full max-w-full text-zinc-50 flex flex-col space-y-16 relative py-10">
      <Header title="Resumo" description="Conheça minhas habilidades" />
    </div>
  );
}
