import { Poppins } from "next/font/google";
import type { Metadata } from "next";

const poppins = Poppins({ weight: "400", style: "normal", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ShinodaLabs | Projetos",
  description: "Generated by create next app",
};

export default function ProjectsLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
      <html lang="pt-BR">
        <body className={poppins.className}>{children}</body><body>{children}</body>
      </html>
    );
  }