import Header from "@/components/Header";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "ShinodaLabs | Projetos",
  description: "Generated by create next app",
};

export default function ProjectsPage() {
  return (
    <div className="w-full max-w-full text-zinc-50 flex flex-col space-y-16 relative py-10">
      <Header title="Projetos" description="Conheça meus projetos" />
    </div>
  );
}
